### ISSUE TITLE
pull queries from tree-sitter language config

### ISSUE THREAD

**Issue by boltlessengineer** [nvim-neorocks/luarocks-build-treesitter-parser#22]
There is [language configuration](https://tree-sitter.github.io/tree-sitter/syntax-highlighting#language-configuration) specifying parser’s information in `package.json` file.

Instead of providing yet another way to add queries in rockspec, we can use the provided queries from official tree-sitter spec.
If that queries aren’t enough or outdated, it should be updated anyways from each parser repos.

**Comment by mrcjkb** [comment]
Hey 👋 

We use the queries from nvim-treesitter, as they often tend to be better tailored to Neovim than the ones bundled with the parser repos.

**Comment by boltlessengineer** [comment]
Thank you for fast reply!

If neovim isn’t working with bundled queries, Neovim should be fixed.
If bundled queries don’t provide enough informations for Neovim, they should add them for all other editors.
If specific parser repo doesn’t update the queries, it means that parser is not maintained.

Where should user make issue when they see error on TS queries from rockspec? For example, javascript queries seem to not working right now because ecma queries are missing.
If user want external query provider, they can rather use nvim-treesitter to include all latest queries at first place.

I can’t see strong reason why neorocks should provide copied third-party queries in rockspec.

**Comment by boltlessengineer** [comment]
Wait, my bad. Just realized there is `tree-sitter-ecma` for ecma queries.
Still can’t get the idea of “including copied version of third-party queries for each parsers” idea though.

**Comment by mrcjkb** [comment]
> If neovim isn’t working with bundled queries, Neovim should be fixed.
If bundled queries don’t provide enough informations for Neovim, they should add them for all other editors.
If specific parser repo doesn’t update the queries, it means that parser is not maintained.

I'm sure that would be ideal, but that's just not the way it is right now. 
In any case: This is not the place to discuss this. You can bring this up with the Neovim/nvim-treesitter teams if you want to (I'm sure they have good reasons for maintaining their own queries).

> Just realized there is tree-sitter-ecma for ecma queries.

Yep, I haven't implemented dependencies for tree-sitter parsers yet. It's on my radar: https://github.com/nvim-neorocks/nurr/issues/7

> If user want external query provider, they can rather use nvim-treesitter to include all latest queries at first place.
> I can’t see strong reason why neorocks should provide copied third-party queries in rockspec.

- nvim-treesitter on `main` (which will eventually become the default branch) no longer provides all queries.
  Instead, it installs queries along with the parsers with `:TSInstall`.
- We bundle the queries with the parsers, because this is the best way to ensure users don't have mismatches (outdated queries or outdated parsers) for highlights.

> Still can’t get the idea of “including copied version of third-party queries for each parsers” idea though.

I have stated my reasons for this.
If it one day turns out that there is a need not to override the queries in the parser repo, we can add a `DONT_INSTALL_NVIM_QUERIES` environment/luarocks config variable.
But for now, I'm saying YAGNI.

**Comment by boltlessengineer** [comment]
Ok fine. Now I get the reason. Sorry for bothering you and thank you for your kind reply.
Dependencies in tree-sitter parsers sounds really cool, haven’t thought about that.
